apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}-ingress
  labels:
    app: {{ template "name" . }}-ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: tlu.j2rvaservud.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ if .Values.varnish.enabled }}varnish{{ else }}api{{ end }}
          servicePort: 80
  tls:
  - hosts:
    - tlu.j2rvaservud.eu
    secretName: tls-secret
